apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-backend-user-rs  #리플리카셋 이름
spec:
  replicas: 2  # 2개의 동일한 파드 유지
  selector:
    matchLabels:
      app: k8s-backend-user  # 관리할 파드 선택 기준
  template:  # 새 파드 생성 템플릿 (원본 Pod 사양과 동일) -> 새로 pod를 생성할 수도 있는데 이때 내용을 알아야 가능하니깐
    metadata:
      labels:
        app: k8s-backend-user  # selector와 일치해야 함
      name: k8s-backend-user  # Pod 이름 (생략 가능, 자동 생성됨)
    spec:
      containers:
      - name: k8s-backend-user
        image: leenagyoung/k8s-backend-user:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080